In [1]:
import json
file_name= 'books_small.json'

In [2]:
# To read first line
with open(file_name) as f:
    for line in f:
        print(line)
        break

{"reviewerID": "A1E5ZR1Z4OQJG", "asin": "1495329321", "reviewerName": "Pure Jonel \"Pure Jonel\"", "helpful": [0, 0], "reviewText": "Da Silva takes the divine by storm with this unique new novel.  She develops a world unlike any others while keeping it firmly in the real world.  This is a very well written and entertaining novel.  I was quite impressed and intrigued by the way that this solid storyline was developed, bringing the readers right into the world of the story.  I was engaged throughout and definitely enjoyed my time spent reading it.I loved the character development in this novel.  Da Silva creates a cast of high school students who actually act like high school students.  I really appreciated the fact that none of them were thrown into situations far beyond their years, nor did they deal with events as if they had decades of life experience under their belts.  It was very refreshing and added to the realism and impact of the novel.  The friendships between the characters i

In [3]:
# for first review text and rating
with open(file_name) as f:
    for line in f:
        review=json.loads(line)
        print(review['reviewText'])
        print(review['overall'])
        
        break

Da Silva takes the divine by storm with this unique new novel.  She develops a world unlike any others while keeping it firmly in the real world.  This is a very well written and entertaining novel.  I was quite impressed and intrigued by the way that this solid storyline was developed, bringing the readers right into the world of the story.  I was engaged throughout and definitely enjoyed my time spent reading it.I loved the character development in this novel.  Da Silva creates a cast of high school students who actually act like high school students.  I really appreciated the fact that none of them were thrown into situations far beyond their years, nor did they deal with events as if they had decades of life experience under their belts.  It was very refreshing and added to the realism and impact of the novel.  The friendships between the characters in this novel were also truly touching.Overall, this novel was fantastic.  I can&#8217;t wait to read more and to find out what happen

In [4]:
# Creating a list with a tuple for reviews and rating
reviews=[]

with open(file_name) as f:
    for line in f:
        review=json.loads(line)
        reviews.append((review['reviewText'], review['overall']))
        
# Printing 6th of reviews list
reviews[5]

('Love the book, great story line, keeps you entertained.for a first novel from this author she did a great job,  Would definitely recommend!',
 4.0)

In [5]:
# Rating of 5
reviews[5][1]

4.0

## LOAD DATA

In [6]:
# Creating a class for Review
class Review:
    def __init__(self, text, score):
        self.text= text
        self.score= score
        self.sentiment= self.get_sentiment()
        
    def get_sentiment(self):
        if self.score<=2:
            return "NEGATIVE"
        elif self.score==3:
            return "NEUTRAL"
        else: #score of 4 or 5
            return "POSITIVE"

In [9]:
# Creating a list with a tuple for reviews and rating
reviews=[]

with open(file_name) as f:
    for line in f:
        review=json.loads(line)
        reviews.append(Review(review['reviewText'], review['overall']))
        
# Printing 6th of reviews list
reviews[5].score

4.0

In [10]:
reviews[8].sentiment

'POSITIVE'

In [11]:
# Above code can also be written as:
'''
class Sentiment:
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    POSITIVE = "POSITIVE"

class Review:
    def __init__(self, text, score):
        self.text = text
        self.score = score
        self.sentiment = self.get_sentiment()
        
    def get_sentiment(self):
        if self.score <= 2:
            return Sentiment.NEGATIVE
        elif self.score == 3:
            return Sentiment.NEUTRAL
'''

'\nclass Sentiment:\n    NEGATIVE = "NEGATIVE"\n    NEUTRAL = "NEUTRAL"\n    POSITIVE = "POSITIVE"\n\nclass Review:\n    def __init__(self, text, score):\n        self.text = text\n        self.score = score\n        self.sentiment = self.get_sentiment()\n        \n    def get_sentiment(self):\n        if self.score <= 2:\n            return Sentiment.NEGATIVE\n        elif self.score == 3:\n            return Sentiment.NEUTRAL\n'

## DATA PREPARATION

In [12]:
len(reviews)

1000

In [13]:
# we have 1000 number of reviews

#### Split the dataset in to trainig and testing sets

In [14]:
from sklearn.model_selection import train_test_split
training, test= train_test_split(reviews, test_size=0.33, random_state=42)

In [15]:
len(training)

670

In [16]:
# We had main dataset i.e. reviews
# Now we have training  and testing dataset i.e. training , test
# We read reviews dataset as: reviews[5].text or reviews[5].score
# Training and test will also read as: training[5].text or training[5].score

In [18]:
print(training[0].score)

5.0


In [19]:
# Now we will transform traing data in text and sentiment as x and y
train_x= [x.text for x in training]
train_y= [x.sentiment for x in training]

In [20]:
train_x[2]

"Mitchell has really gifted us with a gem. He provides a clear and concise methodology for connecting the mind into the meridian channels and acupuncture points. His techniques for dredging the channels, although simple, are remarkably wonderful. I couldn't be happier to have picked this one up. Thanks!"

In [22]:
train_y[2]

'POSITIVE'

In [23]:
# In the same way, do to test data
test_x= [x.text for x in test]
test_y= [x.sentiment for x in test]

## Bag of words Vectorization

In [27]:
# we transform train_x in to bag of words
from sklearn.feature_extraction.text import CountVectorizer

vectorizer= CountVectorizer()
train_x_vectors= vectorizer.fit_transform(train_x)
'''
above line can be writtens as
vectorizer.fit(train_x)
train_x_vector= vectorizer.transform(train_x)
'''
# Transform test_x data too, dont fit it, just transform it
test_x_vectors= vectorizer.transform(test_x)

print(train_x[0])
print(train_x_vectors[0])
print(train_x_vectors[0].toarray())

Vivid characters and descriptions. The author has created a tale that grabs your attention and I couldn't put it down.
  (0, 7086)	1
  (0, 1148)	1
  (0, 350)	2
  (0, 1800)	1
  (0, 6595)	1
  (0, 562)	1
  (0, 3054)	1
  (0, 1558)	1
  (0, 6475)	1
  (0, 6593)	1
  (0, 2895)	1
  (0, 7353)	1
  (0, 539)	1
  (0, 1515)	1
  (0, 5197)	1
  (0, 3545)	1
  (0, 2007)	1
[[0 0 0 ... 0 0 0]]


In [26]:
print(train_x[3])
print(train_x_vectors[3])
print(train_x_vectors[3].toarray())

Felt like I was floating down the river...Solid explaination of cause and effect, with first person follow-up to keep it real.
  (0, 350)	1
  (0, 6595)	1
  (0, 3545)	1
  (0, 2007)	1
  (0, 4582)	1
  (0, 7260)	1
  (0, 6709)	1
  (0, 6974)	1
  (0, 2499)	1
  (0, 3885)	1
  (0, 7133)	1
  (0, 2600)	1
  (0, 5577)	1
  (0, 6076)	1
  (0, 2370)	1
  (0, 1105)	1
  (0, 2131)	1
  (0, 2562)	1
  (0, 4841)	1
  (0, 2625)	1
  (0, 3689)	1
  (0, 5289)	1
[[0 0 0 ... 0 0 0]]


## CLASSIFICATION

### Linear SVM

In [28]:
from sklearn import svm
clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(train_x_vectors, train_y)
print(test_x[0])
clf_svm.predict(test_x_vectors[0])

Every new Myke Cole book is better than the last, and this is no exception. If you haven't read the Shadow Ops series before start with Control Point, but go ahead and order Fortress Frontier and Breach Zone as well - you're going to want them.


array(['POSITIVE'], dtype='<U8')

### Decision Tree

In [29]:
from sklearn.tree import DecisionTreeClassifier

clf_dec=DecisionTreeClassifier()
clf_dec.fit(train_x_vectors, train_y)

clf_dec.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

### Naive Bayes

In [36]:
from sklearn.naive_bayes import GaussianNB
clf_gnb= GaussianNB()
clf_gnb.fit(train_x_vectors, train_y)

clf_gnb.predict(test_x_vectors[2].todense())

TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

In [39]:
# Above code will result in error, so we include todense() train and test vector

from sklearn.naive_bayes import GaussianNB
clf_gnb= GaussianNB()
clf_gnb.fit(train_x_vectors.todense(), train_y)

clf_gnb.predict(test_x_vectors[0].todense())

array(['POSITIVE'], dtype='<U8')

### Logistic Regression

In [40]:
from sklearn.linear_model import LogisticRegression

clf_log=LogisticRegression()
clf_log.fit(train_x_vectors, train_y)

clf_log.predict(test_x_vectors[0])

C:\Users\Abdul Basit\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array(['POSITIVE'], dtype='<U8')

## EVALUATION

In [44]:
# Here we use todense() on naive also
# Mean Accuracy
print(clf_svm.score(test_x_vectors, test_y))
print(clf_dec.score(test_x_vectors, test_y))
print(clf_gnb.score(test_x_vectors.todense(), test_y))
print(clf_log.score(test_x_vectors, test_y))

0.8242424242424242
0.7636363636363637
0.8121212121212121
0.8303030303030303


In [46]:
# F Scores
from sklearn.metrics import f1_score
f1_score(test_y, clf_svm.predict(test_x_vectors), average=None)

array([0.22222222, 0.21052632, 0.91319444])

In [47]:
# Addig labels for deatils explanation for positive, negative and neutral
f1_score(test_y, clf_svm.predict(test_x_vectors), average=None, labels=["POSITIVE","NEUTRAL","NEGATIVE"])

array([0.91319444, 0.21052632, 0.22222222])

In [48]:
# postive= 0.91
# neutral= 0.21
# negative= 0.22

In [49]:
f1_score(test_y, clf_log.predict(test_x_vectors), average=None, labels=["POSITIVE","NEUTRAL","NEGATIVE"])

array([0.91370558, 0.12244898, 0.1       ])

In [52]:
print(train_y.count("POSITIVE"))
print(train_y.count("NEGATIVE"))
print(train_y.count("NEUTRAL"))

552
47
71


In [53]:
# We have more positive data, so data seems very biased

In [55]:
# We use 10000 data json file to ignore biasness

# REPEAT ABOVE WITH 10000 DATA

In [90]:
import random
class Sentiment:
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    POSITIVE = "POSITIVE"

class Review:
    def __init__(self, text, score):
        self.text = text
        self.score = score
        self.sentiment = self.get_sentiment()
        
    def get_sentiment(self):
        if self.score <= 2:
            return Sentiment.NEGATIVE
        elif self.score == 3:
            return Sentiment.NEUTRAL
        else: #Score of 4 or 5
            return Sentiment.POSITIVE
        
class ReviewContainer:
    def __init__(self, reviews):
        self.reviews= reviews
        
    def get_text(self):
        return [x.text for x in self.reviews]
    
    def get_sentiment(self):
        return [x.sentiment for x in self.reviews]
        
    def evenly_distribute(self):
        negative= list(filter(lambda x: x.sentiment == Sentiment.NEGATIVE, self.reviews))
        positive= list(filter(lambda x: x.sentiment == Sentiment.POSITIVE, self.reviews))
        positive_shrunk = positive[:len(negative)]
        self.reviews = negative + positive_shrunk
        random.shuffle(self.reviews)
        
# Evenlydistrubute will distribute pos and neg evenly, neg and pos are equal


In [70]:
# Creating a list with a tuple for reviews and rating
file_name='Books_small_10000.json'
reviews=[]

with open(file_name) as f:
    for line in f:
        review=json.loads(line)
        reviews.append(Review(review['reviewText'], review['overall']))
        
# Printing 6th of reviews list
reviews[5].text

'I hoped for Mia to have some peace in this book, but her story is so real and raw.  Broken World was so touching and emotional because you go from Mia\'s trauma to her trying to cope.  I love the way the story displays how there is no "just bouncing back" from being sexually assaulted.  Mia showed us how those demons come for you every day and how sometimes they best you. I was so in the moment with Broken World and hurt with Mia because she was surrounded by people but so alone and I understood her feelings.  I found myself wishing I could give her some of my courage and strength or even just to be there for her.  Thank you Lizzy for putting a great character\'s voice on a strong subject and making it so that other peoples story may be heard through Mia\'s.'

## DATA PREPARATION

### Split the data into test and train

In [83]:
'''from sklearn.model_selection import train_test_split
training, test= train_test_split(reviews, test_size=0.33, random_state=42)
# Use Evenly distribute for pos and neg
cont= ReviewContainer(training)
cont.evenly_distribute()
len(cont.reviews)'''

872

In [91]:
from sklearn.model_selection import train_test_split

training, test = train_test_split(reviews, test_size=0.33, random_state=42)

train_container = ReviewContainer(training)

test_container = ReviewContainer(test)

In [92]:
train_container.evenly_distribute()
train_x = train_container.get_text()
train_y = train_container.get_sentiment()

test_container.evenly_distribute()
test_x = test_container.get_text()
test_y = test_container.get_sentiment()

print(train_y.count(Sentiment.POSITIVE))
print(train_y.count(Sentiment.NEGATIVE))

436
436


In [93]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# This book is great !
# This book was so bad

vectorizer = TfidfVectorizer()
train_x_vectors = vectorizer.fit_transform(train_x)

test_x_vectors = vectorizer.transform(test_x)

print(train_x[0])
print(train_x_vectors[0].toarray())

It was a book that was fun to read. I've had one problem...is there more to the &#34;free version&#34;, and which is the book following this one?
[[0. 0. 0. ... 0. 0. 0.]]


In [94]:
from sklearn import svm

clf_svm = svm.SVC(kernel='linear')

clf_svm.fit(train_x_vectors, train_y)

test_x[0]

clf_svm.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

In [95]:
from sklearn.tree import DecisionTreeClassifier

clf_dec = DecisionTreeClassifier()
clf_dec.fit(train_x_vectors, train_y)

clf_dec.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

In [96]:
from sklearn.naive_bayes import GaussianNB

clf_gnb = DecisionTreeClassifier()
clf_gnb.fit(train_x_vectors, train_y)

clf_gnb.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

In [97]:
from sklearn.linear_model import LogisticRegression

clf_log = LogisticRegression()
clf_log.fit(train_x_vectors, train_y)

clf_log.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

In [98]:
# Mean Accuracy
print(clf_svm.score(test_x_vectors, test_y))
print(clf_dec.score(test_x_vectors, test_y))
print(clf_gnb.score(test_x_vectors, test_y))
print(clf_log.score(test_x_vectors, test_y))

0.8076923076923077
0.6442307692307693
0.6538461538461539
0.8052884615384616


In [99]:
# F1 Scores
from sklearn.metrics import f1_score

f1_score(test_y, clf_svm.predict(test_x_vectors), average=None, labels=[Sentiment.POSITIVE, Sentiment.NEGATIVE])
#f1_score(test_y, clf_log.predict(test_x_vectors), average=None, labels=[Sentiment.POSITIVE, Sentiment.NEUTRAL, Sentiment.NEGATIVE])

array([0.80582524, 0.80952381])

In [100]:
test_set = ['very fun', "bad book do not buy", 'horrible waste of time']
new_test = vectorizer.transform(test_set)

clf_svm.predict(new_test)

array(['POSITIVE', 'NEGATIVE', 'NEGATIVE'], dtype='<U8')

## Tune the model with gridSearch

In [101]:
from sklearn.model_selection import GridSearchCV

parameters = {'kernel': ('linear', 'rbf'), 'C': (1,4,8,16,32)}

svc = svm.SVC()
clf = GridSearchCV(svc, parameters, cv=5)
clf.fit(train_x_vectors, train_y)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': (1, 4, 8, 16, 32), 'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [102]:
print(clf.score(test_x_vectors, test_y))

0.8197115384615384


### Save the model

In [104]:
import pickle

with open('sentiment_classifier.pkl', 'wb') as f:
    pickle.dump(clf, f)

### Load the model

In [107]:
with open('sentiment_classifier.pkl', 'rb') as f:
    loaded_clf = pickle.load(f)

In [108]:
print(test_x[0])

loaded_clf.predict(test_x_vectors[0])

4 stars. A  grieving reporter and a troubled/frightened woman cross paths on a train just moments before a tragic death. The mystery includes a missing child. I look forward to reading more by this author.


array(['POSITIVE'], dtype='<U8')